### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by zackkrida** [zackkrida/next-codegen#3]
- [ ] #1 Add prettier formatting
- [ ] #2 Add `components` generator
- [x] #4 Add option for page data type
